#! /bin/bash
### BEGIN INIT INFO
# Provides:          gunicorn
# Required-Start:    nginx
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The main django process
# Description:       The gunicorn process that receives HTTP requests
#                    from nginx
#
### END INIT INFO
#
# Author:       Brett Wyer <brett.wyer@gmail.com>
#
APPNAME=gunicorn
USER=pi
GROUP=dialout
PATH=/bin:/usr/bin:/sbin:/usr/sbin
APPMODULE=wsgi:application
DAEMON=/usr/local/bin/gunicorn
BIND=127.0.0.1:8000
PIDFILE=/run/gunicorn/pid
LOGLEVEL=debug
LOGFILE=/var/log/$DAEMON/$DAEMON.log


. /lib/lsb/init-functions


if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi


case "$1" in
  start)
        log_daemon_msg "Starting deferred execution scheduler" "$APPNAME"
        $DAEMON --worker-class=socketio.sgunicorn.GeventSocketIOWorker --timeout=120 --env=POLICY_SERVER=0 --log-level=$LOGLEVEL --log-file=$LOGFILE --pid=$PIDFILE --user=$USER --group=$GROUP $APPMODULE
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping deferred execution scheduler" "APPNAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
